language: csharp
mono: none
matrix:
  include:
    - os: osx
      mono: none
      dotnet: 2.1.300
      before_install:
        - brew update
        - brew install ffmpeg mono-libgdiplus
        - nvm install --lts
        - nvm use --lts
        - node ./.build/travis-ffmpeg-config.js
    - os: linux
      dist: trusty
      dotnet: 2.1.300
      before_install:
        - sudo add-apt-repository -y ppa:mc3man/trusty-media
        - sudo apt-get update
        - sudo apt-get install -y ffmpeg libgdiplus
        - nvm install --lts
        - nvm use --lts
        - node ./.build/travis-ffmpeg-config.js
script:
  - dotnet restore
  - dotnet build ./FFMpegCore/
  - dotnet test -v d ./FFMpegCore.Test/
branches:
  only:
    - master
    - /fix\/.+/
    - /feature\/.+/
